export const LOADING = "LOADING";
export const PRODUCTS = "PRODUCTS";
export const PRODUCT_DETAILS = "PRODUCT_DETAILS";
export const CATEGORIES = "CATEGORIES";
export const SIZES = "SIZES";
export const GET_ALL_PRODUCT_FROM_WATCH_LIST = "GET_ALL_PRODUCT_FROM_WATCH_LIST";
